site_name: network-routing
theme:
theme:
  name: material
  features:
    - navigation.instant
    # - navigation.tabs
    - header.autohide
  icon:
    logo: material/map-marker-path
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/dvrpc/network-routing
repo_name: dvrpc/network-routing
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_if_no_docstring: true
            group_by_category: false

markdown_extensions:
  - pymdownx.tabbed
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - About: index.md
  - Installation & Setup: installation.md
  - Prepare the Database: database.md
  - Sidewalk Gap Analysis: sidewalk_gap_analysis.md
  - Other Analyses: other_analyses.md
  - Network Analysis Methodology: methodology.md
  - Run the Analysis in the Cloud: cloud.md
